Initial code insert
Burkut60/AndroidBeginner pull request #1
Opened 2020-03-24 17:46 UTC by Burkut60

2020-03-24 18:30 UTC, tim-teacher requested changes

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/HelloUser.java
> +public class HelloUser extends Activity {
HelloUserActivity

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/HelloUser.java
> +    Button button;
private

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/HelloUser.java
> +        setContentView(R.layout.activitt_helloo_user);
activity_hello_user

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MainActivity.java
> +                textView2.setText("Краный");
1)
String temp = textView2.getText().toString();
textView2.setText(textView3.getText());
textView3.setText(temp);
2) 
String text2 = textView2.getText().toString();
String text3 = textView3.getText().toString();

textView2.setText(text2);
textView3.setText(text3);

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/res/values/strings.xml
> +    <string name="Button">Кнопка</string>
Лучше с маленькой буквы Button -> button.

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/res/layout/activitt_helloo_user.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Удалить лишний контейнер и оставить только LinearLayout.

2020-03-24 18:30 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
Тут все правильно. onCreate всегда используем с одним параметром.

2020-03-25 19:06 UTC, Burkut60 commented on app/src/main/java/com/example/myapplicationandroid_beginner/HelloUser.java
> +    Button button;
Modifier private not allowed here ( не дает поставить модификатор.)

2020-03-25 19:41 UTC, Burkut60 commented on app/src/main/res/layout/activitt_helloo_user.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Не вижу возможности удалить этот Layout. Пробовал даже создать новый файл и изначально его убрать, нет не получилось. Сразу все подсвечивается красным.

2020-03-31 11:59 UTC, closed without merging