LoginLinearActivity
Burkut60/AndroidBeginner pull request #4
Opened 2020-04-06 18:54 UTC by Burkut60

homework Login Linear Activity

2020-04-06 20:18 UTC, tim-teacher requested changes

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MenuActivity.java
> +            case R.id.buttonLoginId:
buttonLoginId -> loginButton

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MenuActivity.java
> +            case R.id.buttonLoginId:
переименовать

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/TextExchangeActivity.java
> +        Button button = findViewById(R.id.button1Activity);
У тебя задание LoginActivity, TextExchangeActivity уже была сделана? этих изменений не должно быть тут, это очень строгое правило в компаниях. В пул реквесте должно быть только то что относиться к данной задаче, если нужно что то подправить в других файлах, то нужно делать другой пул реквест.

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +    android:scaleType="centerCrop">
android:scaleType="centerCrop" это только для картинок используется, для LinearLayout такого атрибута нет.

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +            android:id="@+id/logpId"
rename logpId -> logoImage

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +            android:id="@+id/UserNameId"
rename UserNameId -> userNameText

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +            android:id="@+id/PasswordId"
rename PasswordId -> passwordText

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +            android:id="@+id/logInId"
rename

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +            android:id="@+id/forgotId"
rename

2020-04-06 20:18 UTC, tim-teacher commented on app/src/main/res/layout/activity_flags.xml
> +        android:id="@+id/linearFlag"
флаги нужно убрать из этого пул реквеста

2020-04-07 11:26 UTC, Burkut60 commented on app/src/main/java/com/example/myapplicationandroid_beginner/TextExchangeActivity.java
> +        Button button = findViewById(R.id.button1Activity);
Понял

2020-04-07 17:17 UTC, tim-teacher requested changes

2020-04-07 17:17 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MenuActivity.java
> +        Button buttonFlagsActivity = findViewById(R.id.button1Activity);
button1Activity -> flagActivityButton

2020-04-07 17:17 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MenuActivity.java
>          Button buttonTextExChange = findViewById(R.id.buttonTrxtExChange);
buttonTrxtExChange -> textExchangeButton

2020-04-07 17:17 UTC, tim-teacher commented on app/src/main/java/com/example/myapplicationandroid_beginner/MenuActivity.java
> +        Button buttonFlagsActivity = findViewById(R.id.button1Activity);
и также переменных названия переменных

2020-04-07 17:17 UTC, tim-teacher commented on app/src/main/res/layout-v23/activity_login_linear.xml
> +        <LinearLayout
Я думаю этот LinearLayout лишний, ты же можешь сразу положить все это содержимое во внешний LinearLayout, а тот где нижняя кнопка там стоит вес 1, тоесть он займет все оставшееся место и все будет ок.

2020-04-08 19:33 UTC, merged